TimeBundle\Entity\DailySchedule:
    type: entity
    table: null
    repositoryClass: TimeBundle\Repository\DailyScheduleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        isDone:
            type: boolean
            nullable: true
        date:
            type: date
            
    manyToOne:
        taskInSchedule:
            targetEntity: Task
            inversedBy: taskSchedule
            fetch: EAGER
            joinColumn:
                name: taskId
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE
   
        userInSchedule:
            targetEntity: User
            inversedBy: userSchedule
            joinColumn:
                name: userId
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
                onUpdate: CASCADE

    
    lifecycleCallbacks: {  }
