TimeBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: TimeBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        taskName:
            type: string
            length: 255
            nullable: false
            unique: true
            
        schedule:
            type: integer
            
    manyToOne:
        creator:
            targetEntity: User
            inversedBy: createdTasks
            joinColumn:
                name: user
                referencedColumnName: id
                nullable: false
                
     
    oneToMany:
        taskSchedule:
            targetEntity: DailySchedule
            mappedBy: taskInSchedule
            
            
    lifecycleCallbacks: {  }
