TimeBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: TimeBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fname:
            type: string
            length: '50'
            nullable: false
        lname:
            type: string
            length: '50'
            nullable: false
        username:
            type: string
            length: '100'
            nullable: false
            unique: true
        password:
            type: string
            length: '100'
            nullable: false
        age:
            type: integer
            nullable: false
        role:
            type: integer
            nullable: false
        
        
    
    manyToOne:
        children:
            targetEntity: User
            inversedBy: mother
            joinColumn:
                name: mother_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE
                onUpdate: CASCADE
            
    
    oneToMany:
        createdTasks:
            targetEntity: Task
            mappedBy: creator
            
        userSchedule:
            targetEntity: DailySchedule
            mappedBy: userInSchedule
    
        mother:
            targetEntity: User
            mappedBy: children
        
        
    lifecycleCallbacks: {  }
