api_dailySchedule:
    resource: "@TimeBundle/Resources/config/routing/dailySchedule.yml"

api_login:
    path:   /login_check
    defaults: { _controller: "TimeBundle:ApiDailySchedule:test" }
    methods:  [POST ]
    
api_test:
    path:   /test
    defaults: { _controller: "TimeBundle:ApiDailySchedule:test" }
    methods:  GET