api_dailySchedule_change:
    path:   /today/{schedule_id}/{state}
    defaults: { _controller: "TimeBundle:ApiDailySchedule:changeScheduleState", state:1 }
    methods:  [POST ,GET]
    requirements:
        schedule_id: '\d+'

api_test:
    path:   /login_check
    defaults: { _controller: "TimeBundle:ApiDailySchedule:test" }
    methods:  [POST ]