dailyschedule_index:
    path:     /
    defaults: { _controller: "TimeBundle:DailySchedule:showUserSchedule" }
    methods:  GET

dailyschedule_show:
    path:     /today
    defaults: { _controller: "TimeBundle:DailySchedule:showTodaySchedule" }
    methods:  GET

dailyschedule_done:
    path:   /today/{schedule_id}
    defaults: { _controller: "TimeBundle:DailySchedule:scheduleDone" }
    methods:  [POST ,GET]

