dailySchedule_index:
    path:     /child/{child_id}
    defaults: { _controller: "TimeBundle:DailySchedule:showChildSchedule" }
    methods:  GET
    requirements:
        child_id: '\d+'

dailySchedule_show:
    path:     /child/{child_id}/today
    defaults: { _controller: "TimeBundle:DailySchedule:showChildTodaySchedule" }
    methods:  GET
    requirements:
        child_id: '\d+'   

dailySchedule_change_state:
    path:   /today/task/{task_id}/state
    defaults: { _controller: "TimeBundle:DailySchedule:changeScheduleState" }
    methods:  [POST]
    requirements:
        schedule_id: '\d+'