mother_show_my_children:
    path:     /{motherId}/showMyChildren
    defaults: { _controller: TimeBundle:Mother:showMyChildren }
    methods:  GET

mother_add_child:
    path:     /addChild
    defaults: { _controller: TimeBundle:Mother:addChild }
    methods:  [GET, POST]

#mother_show_my_children_tasks:
#    path:     /{mother_id}/showMyChildrenTasks
#    defaults: { _controller: TimeBundle:Mother:showMyChildrenTasks }
#    methods:  GET


