task_index:
    path:     /tasks/
    defaults: { _controller: "TimeBundle:Task:index" }
    methods:  GET

task_show:
    path:     /task/{task_id}/show
    defaults: { _controller: "TimeBundle:Task:show" }
    methods:  GET
    requirements:
        task_id: '\d+'

task_new:
    path:     /task/new
    defaults: { _controller: "TimeBundle:Task:new" }
    methods:  [GET, POST]

#task_edit:
#    path:     /task/{task_id}/edit
#    defaults: { _controller: "TimeBundle:Task:edit" }
#    methods:  [GET, POST]
#    requirements:
#        task_id: '\d+'

task_delete:
    path:     /task/{task_id}/delete
    defaults: { _controller: "TimeBundle:Task:delete" }
    methods:  DELETE
    requirements:
        task_id: '\d+'

task_filter:
    path:   /tasks/{page}/filter
    defaults: { _controller: "TimeBundle:Task:filter", page:1 }
    methods:  GET
    requirements:
        page: '\d+'