<?php

namespace TimeBundle\Repository;

use TimeBundle\Entity\DailySchedule;
/**
 * DailyScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChildDailySchedules($childId)
    {
        return $this->createQueryBuilder('schedule')
                ->select()
                ->where("schedule.userInSchedule = $childId")
                ->orderBy('schedule.date', 'ASC')
                ->getQuery()
                ->execute();
    }
    
    public function getChildTodaySchedule($childId){
        $today = new \DateTime();
        $today = $today->format('y-m-d');
//        dump($today->format('y-m-d'));
//        die();
        return $this->createQueryBuilder('schedule')
                ->select()
                ->where("schedule.userInSchedule = $childId")
                ->andWhere("schedule.date = '$today'")
                ->getQuery()
                ->execute();
    }
    
    public function createDailySchedule($childId, $taskId, $date)
    {
        $dailySchedule = new DailySchedule();
        $dailySchedule->setDate($date)
                ->setTaskInSchedule($taskId)
                ->setUserInSchedule($childId)
                ->setIsDone(FALSE);
        $entityManager = $this->getEntityManager();
        $entityManager->persist($dailySchedule);
        $entityManager->flush();    
        return $dailySchedule;
    }
    
}
