<?php

namespace TimeBundle\Repository;

/**
 * DailyScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    
}
