<?php

namespace TimeBundle\Repository;
use TimeBundle\constant\Roles;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdminTasks()
    {
        $admin_id = $this->getEntityManager()->getRepository('TimeBundle:User')->getAdminId();
        return $this->createQueryBuilder('task')
                ->select()
                ->where("task.creator = $admin_id")
                ->getQuery()
                ->execute();
    }
    public function getMotherTasks($mother_id)
    {
        return $this->createQueryBuilder('task')
                ->select()
                ->where("task.creator = $mother_id")
                ->getQuery()
                ->execute();
        
    }
}
