<?php

namespace TimeBundle\Repository;

use TimeBundle\constant\Roles;
use TimeBundle\Entity\Task;
use TimeBundle\Entity\User;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function createTask($taskName , $schedule ,$creator)
    {
        $task = new Task();
        $task->setTaskName($taskName)
                ->setCreator($creator)
                ->setSchedule($schedule);
        
        $entityManager = $this->getEntityManager();
        $entityManager->persist($task);
        $entityManager->flush();    
        return $task;
                
    }
    
    public function deleteTask($task_id)
    {
        $this->createQueryBuilder('task')
                ->delete()
                ->where("task.id = $task_id")
                ->getQuery()
                ->execute();
    }

    public function getAdminTasks()
    {
        $adminId = $this->getEntityManager()->getRepository('TimeBundle:User')->getAdminId();
        return $this->createQueryBuilder('task')
                ->select()
                ->where("task.creator = $adminId")
//                ->andWhere("task.schedule = 0 OR task.schedule = $todayAsSchedule")
                ->getQuery()
                ->execute();
        
    }
    
    public function getTodayChildTasks($todayAsSchedule, $motherId)
    {
        $today = new \DateTime();
        $today = $today->format('Y-m-d');
        
        $adminId = $this->getEntityManager()->getRepository('TimeBundle:User')->getAdminId();
        dump( $this->createQueryBuilder('task')
                ->select('task , schedule.isDone')
                ->leftJoin('TimeBundle:DailySchedule', 'schedule','WITH',"task.id = schedule.id AND schedule.date = '$today'")
                ->where("task.schedule = 0 OR task.schedule = $todayAsSchedule")
                ->andWhere("task.creator = $adminId OR task.creator = $motherId")
                ->getQuery()
                ->execute());
        die();
    }


    public function getMotherTasks($motherId)
    {
        return $this->createQueryBuilder('task')
                ->select()
                ->where("task.creator = $motherId")
                ->getQuery()
                ->execute();
    }
    
    public function getAllMothersTasks()
    {
        $role = Roles::ROLE_MOTHER ;
        $subquery = $this->getEntityManager()->getRepository('TimeBundle:User')->createQueryBuilder('user')
                ->select('user.id')
                ->where("user.role = $role")
                ->getDQL();
        
        $qb = $this->createQueryBuilder('task');
        $mothersTasks = $this->createQueryBuilder('task')->select()
                ->where($qb->expr()->in('task.creator', $subquery))
                ->getQuery()
                ->getArrayResult();
        
        return $mothersTasks ;
        
    }
}
