<?php

namespace TimeBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChildrenQueryBuilder()
    {
      return $this->createQueryBuilder('user')
                ->select()
                ->where('user.role = 3');

    }
}
