time_task:
    resource: "@TimeBundle/Resources/config/routing/task.yml"
    
time_user:
    resource: "@TimeBundle/Resources/config/routing/user.yml"

time_dailySchedule:
    resource: "@TimeBundle/Resources/config/routing/dailySchedule.yml"
    prefix:   /dailyschedule
    
time_api:
    resource: "@TimeBundle/Resources/config/routing/api.yml"
    prefix:   /api
    
time_mother:
    resource: "@TimeBundle/Resources/config/routing/mother.yml"
    prefix:   /mother

time_homepage:
    path:     /
    defaults: { _controller: TimeBundle:Security:login }

login:
    path:     /login
    defaults: { _controller: TimeBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: TimeBundle:Security:logout }
    
login_redirection:
    path:   /redirect
    defaults: { _controller: TimeBundle:Security:redirect }

mother_registration:
    path:     /register
    defaults: { _controller: TimeBundle:Mother:motherRegistration }
    methods:  [GET, POST]