time_task:
    resource: "@TimeBundle/Resources/config/routing/task.yml"
    prefix:   /task
    
time_user:
        resource: "@TimeBundle/Resources/config/routing/user.yml"
        prefix:   /user

time_dailySchedule:
    resource: "@TimeBundle/Resources/config/routing/dailySchedule.yml"
    prefix:   /dailyschedule
    
time_mother:
    resource: "@TimeBundle/Resources/config/routing/mother.yml"
    prefix:   /mother

time_homepage:
    path:     /
    defaults: { _controller: TimeBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: TimeBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: TimeBundle:Security:logout }

mother_registration:
    path:     /register
    defaults: { _controller: TimeBundle:Mother:motherRegistration }
    methods:  [GET, POST]